FROM mhart/alpine-node:10
# get rid of annoying warning
RUN npm install -g npm@6.4.0

ARG APP_WORKDIR
WORKDIR $APP_WORKDIR
COPY package*.json $APP_WORKDIR/

# Need build dependencies
RUN npm install --development

COPY ./.babelrc $APP_WORKDIR
COPY ./webpack.config.js $APP_WORKDIR
COPY ./src $APP_WORKDIR/src
COPY ./build $APP_WORKDIR/build

CMD ["sh", "build/dev.sh"]
